# Module 02 : Multivariate Linear Regression

*Summary: Building on what you did on the previous modules you will extend the linear
regression to handle more than one features. Then you will see how to build polynomial
models and how to detect overfitting.*

## Notions of the module
Multivariate linear hypothesis, multivariate linear gradient descent, polynomial models. 
Training and test sets, overfitting.

## Useful Ressources  
  
You are strongly advise to use the following resource:
[Machine Learning MOOC - Stanford](https://www.coursera.org/learn/machine-learning/home/week/2)  
Here are the sections of the MOOC that are relevant for today's exercises: 

### Week 2: 

**Multivariate Linear Regression:**
* Multiple Features (Video + Reading)
* Gradient Descent for Multiple Variables (Video + Reading)
* Gradient Descent in Practice I- Feature Scaling (Video + Reading)
* Gradient Descent in Practice II- Learning Rate (Video + Reading)
* Features and Polynomial Regression (Video + Reading)
* Review (Reading + Quiz)

## General rules
See directly the 42Paris intra subject or the corresponding repository on the [github of 42AI](https://github.com/42-AI/bootcamp_machine-learning)


## Helper

Ensure that you have the right Python interpreter (at least 3.7).

## Note:
```git push --quiet github``` to push on github when working from the vogsphere repository

# NEED TO BEFORE START:
* execute the script of ex08, because it takes time
* execute the script of ex10, because it takes time

## Exercise 00 - Multivariate Hypothesis - Iterative Version

In [ ]:
import numpy as np
from ex00.prediction import simple_predict

x = np.arange(1,13).reshape((4,3))
print("# Example 0:")
theta1 = np.array([[5],[0],[0],[0]])
pred = simple_predict(x, theta1)
# Ouput:
# array([[5.],[ 5.],[ 5.],[ 5.]])
# Do you understand why y_hat contains only 5’s here?
expected_pred = np.array([[5.],[ 5.],[ 5.],[ 5.]])
print("my prediction:".ljust(25), pred.reshape(1, -1))
print("expected prediction:".ljust(25), pred.reshape(1, -1))


print("\n# Example 1:")
theta2 = np.array([[0],[1],[0],[0]])
pred = simple_predict(x, theta2)
# Output:
# array([[ 1.],[ 4.],[ 7.],[ 10.]])
# Do you understand why y_hat == x[:,0] here?
expected_pred = np.array([[ 1.],[ 4.],[ 7.],[ 10.]])
print("my prediction:".ljust(25), pred.reshape(1, -1))
print("expected prediction:".ljust(25), expected_pred.reshape(1, -1))


print("\n# Example 2:")
theta3 = np.array([[-1.5],[0.6],[2.3],[1.98]])
pred = simple_predict(x, theta3)
# Output:
# array([[ 9.64],[ 24.28],[ 38.92],[ 53.56]])
expected_pred = np.array([[ 9.64],[ 24.28],[ 38.92],[ 53.56]])
print("my prediction:".ljust(25), pred.reshape(1, -1))
print("expected prediction:".ljust(25), expected_pred.reshape(1, -1))


print("\n# Example 3:")
theta4 = np.array([[-3],[1],[2],[3.5]])
pred = simple_predict(x, theta4)
# Output:
# array([[12.5],[ 32. ],[ 51.5],[ 71. ]])
expected_pred = np.array([[12.5],[ 32. ],[ 51.5],[ 71. ]])
print("my prediction:".ljust(25), pred.reshape(1, -1))
print("expected prediction:".ljust(25), expected_pred.reshape(1, -1))

## Exercise 01 - Mulltivariate hypothesis - Vectorized Version

In [ ]:
import numpy as np
from ex01.prediction import predict_

x = np.arange(1,13).reshape((4,-3))
print("# Example 0:")
theta1 = np.array([[5],[ 0],[ 0],[ 0]])
pred = predict_(x, theta1)
# Ouput:
# array([[5.],[ 5.],[ 5.],[ 5.]])
# Do you understand why y_hat contains only 5’s here?
expected_pred = np.array([[5.],[ 5.],[ 5.],[ 5.]])
print("my prediction:".ljust(25), pred.reshape(1, -1))
print("expected prediction:".ljust(25), expected_pred.reshape(1, -1))

print("\n# Example 1:")
theta2 = np.array([[0],[ 1],[ 0],[ 0]])
pred = predict_(x, theta2)
# Output:
# array([[ 1.],[ 4.],[ 7.],[ 10.]])
# Do you understand why y_hat == x[:,0] here?
expected_pred = np.array([[1.],[ 4.],[ 7.],[ 10.]])
print("my prediction:".ljust(25), pred.reshape(1, -1))
print("expected prediction:".ljust(25), expected_pred.reshape(1, -1))

print("\n# Example 2:")
theta3 = np.array([[-1.5],[ 0.6],[ 2.3],[ 1.98]])
pred = predict_(x, theta3)
# Output:
# array([[ 9.64],[ 24.28],[ 38.92],[ 53.56]])
expected_pred = np.array([[ 9.64],[ 24.28],[ 38.92],[ 53.56]])
print("my prediction:".ljust(25), pred.reshape(1, -1))
print("expected prediction:".ljust(25), expected_pred.reshape(1, -1))

print("\n# Example 3:")
theta4 = np.array([[-3],[ 1],[ 2],[ 3.5]])
pred = predict_(x, theta4)
# Output:
# array([[12.5],[ 32. ],[ 51.5],[ 71. ]])
expected_pred = np.array([[12.5],[ 32. ],[ 51.5],[ 71. ]])
print("my prediction:".ljust(25), pred.reshape(1, -1))
print("expected prediction:".ljust(25), expected_pred.reshape(1, -1))

## Exercise 02 - Vectorized Loss Function

In [ ]:
import numpy as np
from ex02.loss import loss_

X = np.array([[0],[ 15],[ -9],[ 7],[ 12],[ 3],[ -21]])
Y = np.array([[2],[ 14],[ -13],[ 5],[ 12],[ 4],[ -19]])

print("# Example 0:")
loss = loss_(X, Y)
expected_loss = 2.1428571428571436
print("my loss: ".ljust(20), loss)
print("expected loss: ".ljust(20), expected_loss)

print("\n# Example 1:")
loss = loss_(X, X)
expected_loss = 0.0
print("my loss: ".ljust(20), loss)
print("expected loss: ".ljust(20), expected_loss)

## Exercise 03 - Multivariate Gradient

In [ ]:
import numpy as np
from ex03.gradient import gradient

x = np.array([[ -6, -7, -9],
              [ 13, -2, 14],
              [ -7, 14, -1],
              [ -8, -4, 6],
              [ -5, -9, 6],
              [ 1, -5, 11],
              [ 9, -11, 8]])
y = np.array([[2],[ 14],[ -13],[ 5],[ 12],[ 4],[ -19]])

print("# Example 0:")
theta1 = np.array([[0],[ 3],[ 0.5],[ -6]])
grad = gradient(x, y, theta1)
# Output:
expected_grad = np.array([[ -33.71428571],[ -37.35714286],[ 183.14285714],[ -393.]])
print("my gradient:".ljust(20), grad.reshape(1, -1))
print("expected gradient:".ljust(20), expected_grad.reshape(1, -1))

print("\n# Example 1:")
theta2 = np.array([[0],[ 0],[ 0],[ 0]])
grad = gradient(x, y, theta2)
# Output:
expected_grad = np.array([[ -0.71428571],[ 0.85714286],[ 23.28571429],[ -26.42857143]])
print("my gradient:".ljust(20), grad.reshape(1, -1))
print("expected gradient:".ljust(20), expected_grad.reshape(1, -1))

## Exercise 04 - Multivariate Gradient Descent

In [ ]:
import numpy as np
from ex04.fit import fit_
from utils.prediction import predict_


x = np.array([[0.2, 2., 20.], [0.4, 4., 40.], [0.6, 6., 60.], [0.8, 8., 80.]])
y = np.array([[19.6], [-2.8], [-25.2], [-47.6]])
theta = np.array([[42.], [1.], [1.], [1.]])


print("# Example 0:")
nw_theta = fit_(x, y, theta, alpha = 0.0005, max_iter=42000)
# Output:
expected_theta = np.array([[41.99],[0.97], [0.77], [-1.20]])
print("initial value of theta:".ljust(40), theta.reshape(1,-1))
print("After training value of theta:".ljust(40), nw_theta.reshape(1, -1))
print("After training expected value of theta:".ljust(40), expected_theta.reshape(1, -1))


print("\n# Example 1:")
pred = predict_(x, nw_theta)
# Output:
# np.array([[19.5992..], [-2.8003..], [-25.1999..], [-47.5996..]])
expected_pred = np.array([[19.5992], [-2.8003], [-25.1999], [-47.5996]])
print("my prediction:".ljust(20), pred.reshape(1,-1))
print("expected prediction:".ljust(20), expected_pred.reshape(1,-1))

## Exercise 05 - Multivariate Linear Regression With Class

In [ ]:
import numpy as np
from ex05.mylinearregression import MyLinearRegression as MyLR

X = np.array([[1., 1., 2., 3.], [5., 8., 13., 21.], [34., 55., 89., 144.]])
Y = np.array([[23.], [48.], [218.]])
mylr = MyLR([[1.], [1.], [1.], [1.], [1]])

print("# Example 0:")
pred = mylr.predict_(X)
# Output:
expected_pred = np.array([[8.], [48.], [323.]])
print("my prediction:".ljust(20), pred.reshape(1, -1))
print("expected prediction:".ljust(20), pred.reshape(1, -1))


print("\n# Example 1:")
loss_e = mylr.loss_elem_(X,Y)
# Output:
expected_loss_e = np.array([[225.], [0.], [11025.]])
print("my loss elem:".ljust(20), loss_e.reshape(1, -1))
print("expected loss elem:".ljust(20), expected_loss_e.reshape(1, -1))


print("\n# Example 2:")
loss = mylr.loss_(X,Y)
# Output:
expected_loss = 1875.0
print("my loss:".ljust(15), loss)
print("expected loss:".ljust(15), expected_loss)


print("\n# Example 3:")
mylr.alpha = 1.6e-4
mylr.max_iter = 200000
mylr.fit_(X, Y)
# Output:
expected_thetas = np.array([[18.188], [2.767], [-0.374], [1.392], [0.017]])
print("my theta after training:".ljust(25), mylr.thetas.reshape(1, -1))
print("expected theta after training:".ljust(25), expected_thetas.reshape(1, -1))


print("\n# Example 4:")
pred = mylr.predict_(X)
# Output:
expected_pred = np.array([[23.417], [47.489], [218.065]])
print("my prediction:".ljust(25), pred.reshape(1, -1))
print("expected prediction:".ljust(25), expected_pred.reshape(1, -1))


print("\n# Example 5:")
loss_e = mylr.loss_elem_(X,Y)
# Output:
expected_loss_e = np.array([[0.174], [0.260], [0.004]])
print("my loss elem:".ljust(25), loss_e.reshape(1, -1))
print("expected loss elem:".ljust(25), expected_loss_e.reshape(1, -1))

print("\n# Example 6:")
loss = mylr.loss_(X,Y)
# Output:
expected_loss = 0.0732
print("my loss:".ljust(15), loss)
print("expected loss:".ljust(15), expected_loss)

## Exercise 06 - Practicing Multivariate Linear Regression

In [ ]:
# Use the python script directly in in folder ex06

## Exercise 07 - Polynomial models

In [ ]:
import numpy as np
from ex07.polynomial_model import add_polynomial_features

x = np.arange(1,6).reshape(-1, 1)

print("# Example 0:")
print(add_polynomial_features(x, 0))
# Output:
# array([[ 1.],
#        [ 1.],
#        [ 1.],
#        [ 1.],
#        [ 1.]])

print("# Example 1:")
print(add_polynomial_features(x, 1))
# Output:
# array([[ 1],
#        [ 2],
#        [ 3],
#        [ 4],
#        [ 5]])

print("# Example 2:")
print(add_polynomial_features(x, 2))
# Output:
# array([[ 1,  1],
#        [ 2,  4],
#        [ 3,  9],
#        [ 4, 16],
#        [ 5, 25]])

print("# Example 3:")
print(add_polynomial_features(x, 3))
# Output:
# array([[ 1,  1,   1],
#        [ 2,  4,   8],
#        [ 3,  9,  27],
#        [ 4, 16,  64],
#        [ 5, 25, 125]])

print("\n# Example 1:")
print(add_polynomial_features(x, 6))
# Output:
# array([[ 1,  1,   1,   1,    1,    1],
#        [ 2,  4,   8,  16,   32,   64],
#        [ 3,  9,  27,  81,  243,  729],
#        [ 4, 16,  64, 256, 1024, 4096],
#        [ 5, 25, 125, 625, 3125, 15625]])


## Exercise 08 - Let's Train Polynomial Models!

In [ ]:
# Use the python script directly in in folder ex08

## Exercise 09 - DataSpliter

In [ ]:
import numpy as np
from ex09.data_spliter import data_spliter

np.random.seed(42)
x1 = np.array([[1],[ 42],[ 300],[ 10],[ 59]])
y = np.array([[0],[1],[0],[1],[0]])

print("# Example 0:")
split = data_spliter(x1, y, 0.8)
for arr in split:
    print(arr)
# Output:
# (array([[ 10],
#         [ 42],
#         [  1],
#         [300]]),
#  array([[59]]),
#  array([[1],
#         [1],
#         [0],
#         [0]]),
#  array([[0]]))

print("\n# Example 1:")
split = data_spliter(x1, y, 0.5)
for arr in split:
    print(arr)
# Output:
#(array([[42],
#        [10]]),
# array([[ 59],
#        [300],
#        [ 1]]),
#  array([[1],
#         [1]]),
#  array([[0],
#         [0],
#         [0]]))
x2 = np.array([[  1, 42],
               [300, 10],
               [ 59,  1],
               [300, 59],
               [ 10, 42]])
y = np.array([[0],[1],[0],[1],[0]])


print("\n# Example 2:")
split = data_spliter(x2, y, 0.8)
for arr in split:
    print(arr)
# Output:
# (array([[10, 42],
#         [59,  1],
#         [ 1, 42],
#         [300, 10]]),
#  array([[300, 59]]),
#  array([[0],
#         [0],
#         [0],
#         [1]]),
#  array([[1]]))


print("\n# Example 3:")
split = data_spliter(x2, y, 0.5)
for arr in split:
    print(arr)
# Output:
# (array([[300, 10],
#         [  1, 42]]),
#  array([[ 10, 42],
#         [300, 59],
#         [ 59,  1]]),
#  array([[1],
#         [0]]),
#  array([[0],
#         [1],
#         [0]]))

## Exercise 10 - Machine Learning for Grown-ups: Training and Test Sets

In [ ]:
# Use the python scripts directly in in folder ex10